---
title: "Syllabus: STAT 545 A (Part I)"
date-modified: last-modified
---

### Acknowledgement

UBC’s Point Grey Campus is located on the traditional, ancestral, and unceded territory of the xwməθkwəyəm (Musqueam) people. The land it is situated on has always been a place of learning for the Musqueam people, who for millennia have passed on their culture, history, and traditions from one generation to the next on this site.

### Course Information

+----------------------------------+-----------------+----------------------+------------------------------------+--------------------+
| **Course Title**                 | **Course Code** | **Credit** **Value** | **Class Times**                    | **Class Location** |
+----------------------------------+-----------------+----------------------+------------------------------------+--------------------+
| Exploratory Data Analysis Part I | STAT 545 A      | 1.5                  | Monday/Wednesday: 9:00am - 10:20am | CHBE 102           |
+----------------------------------+-----------------+----------------------+------------------------------------+--------------------+

### Prerequisites

While there are no formal pre-requisites for STAT 545 A, students should be familiar with basic statistical analyses and have taken at least one introductory statistics course.

STAT545 A is a pre-requisite for STAT545 B. No exceptions.

### Contact and Office Hours

+-----------------+------------------------+-----------------+-----------------------------+
| Instructor      | Contact Details        | Office Location | Office Hours                |
+=================+========================+=================+=============================+
| Grace Tompkins  | grace\<at\>stat.ubc.ca | ESB 3134        | Wednesdays, 2:30pm - 3:30pm |
+-----------------+------------------------+-----------------+-----------------------------+

+---------------------------+------------------------------+-------------------+
| Teaching Assistants (TAs) | Office Hours                 | Location          |
+===========================+==============================+===================+
| Erick Navarro             | Thursdays, 11:00am - 12:00pm | Zoom (See Canvas) |
+---------------------------+------------------------------+-------------------+
| Asfar Lathif              | Mondays, 3:00pm - 4:00pm     | Zoom (See Canvas) |
+---------------------------+------------------------------+-------------------+
| Mario Gomez Camacho       | Wednesdays, 1:00pm - 2:00pm  | Zoom (See Canvas) |
+---------------------------+------------------------------+-------------------+

### Course Structure

This course will feature short lectures and in-class demonstrations so students get hands-on experience with the help of their instructor and TAs. Dedicated time will be given in lecture for students to work through assigned worksheets.

**Please bring a charged laptop to every class.** If you do not have a personal laptop, one can be borrowed through the [UBC library](https://wiki.ubc.ca/Library:Technology_Borrowing/Laptop_Lending).

### Schedule of Topics

**STAT 545 A (Part I):**

+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
| Week    | Date           | Topic                                                                                                                         | In-class work                                                                                                          |
+=========+================+===============================================================================================================================+========================================================================================================================+
| 1       | Tues. Sept 2   | [Installation](../lectures_i/lec1a_installation.qmd)                                                                          | Install Software                                                                                                       |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
|         | Thurs. Sept 4  | [Intro to STAT545 and R](../lectures_i/lec1b_introR.qmd)                                                                      | [Worksheet A1](https://github.com/UBC-STAT/STAT545.github.io/blob/main/content/worksheets_student/worksheet_a01.ipynb) |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
|         |                |                                                                                                                               |                                                                                                                        |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
| 2       | Tues. Sept 9   | [Reproducibility with RMarkdown](../lectures_i/lec2A_reproducibility.qmd)                                                     |                                                                                                                        |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
|         | Thurs. Sept 11 | [Version Control](../lectures_i/lec2b_versioncontrol.qmd)                                                                     |                                                                                                                        |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
|         |                |                                                                                                                               |                                                                                                                        |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
| 3       | Tues. Sept 16  | [Data Manipulation with `dplyr`](../lectures_i/lec3_dplyr.qmd)                                                                | [Worksheet A2](https://github.com/UBC-STAT/STAT545.github.io/blob/main/content/worksheets_student/worksheet_a02.ipynb) |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
|         | Thurs. Sept 18 |                                                                                                                               | Worksheet A2                                                                                                           |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
|         |                |                                                                                                                               |                                                                                                                        |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
| 4       | Tues.. Sept 23 | [Data Visualization](../lectures_i/lec4_datavis.qmd)                                                                          | [Worksheet A3](https://github.com/UBC-STAT/STAT545.github.io/blob/main/content/worksheets_student/worksheet_a03.ipynb) |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
|         | Thurs. Sept 25 |                                                                                                                               | Worksheet A3                                                                                                           |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
|         |                |                                                                                                                               |                                                                                                                        |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
| 5       | Tues. Sept 30  | **\*\*\* NO CLASS \*\*\***                                                                                                    |                                                                                                                        |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
|         | Thurs. Oct 2   | [Tidy Data](../lectures_i/lec5_tidydata.qmd)                                                                                  | [Worksheet A4](https://github.com/UBC-STAT/STAT545.github.io/blob/main/content/worksheets_student/worksheet_a04.ipynb) |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
|         |                |                                                                                                                               |                                                                                                                        |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
| 6       | Tues. Oct 7    | [Model Fitting](../lectures_i/lec6a_modelfitting.qmd)                                                                         | Worksheet A4                                                                                                           |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
|         | Thurs. Oct 9   | [Factors and Dates](../lectures_i/lec6b_dates.qmd)                                                                            | [Worksheet A5](https://github.com/UBC-STAT/STAT545.github.io/blob/main/content/worksheets_student/worksheet_a05.ipynb) |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
|         |                |                                                                                                                               |                                                                                                                        |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
| 7       | Tues. Oct 14   | [Reading and Writing Data](../lectures_i/lec7a_readwritedata.qmd), and [Tibble Joins](../lectures_i/lec7b_joiningtibbles.qmd) | Worksheet A5                                                                                                           |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
|         | Thurs. Oct 16  | Review and Work Session                                                                                                       | Worksheet A5                                                                                                           |
|         |                |                                                                                                                               |                                                                                                                        |
|         |                |                                                                                                                               | [Mini Data Analysis (MDA)](../mda/mda_deliverable1.qmd)                                                                |
+---------+----------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+

This schedule is subject to change. Any changes will be announced via the `#annoucements` channel on Slack, and major changes will be sent out via email.

### Assessments

This course will have autograded, formative worksheets meant to guide you through a number of exercises.

+--------------------------------------------------------------------+----------------------+------------------------------------------------------------------------+
| Assessment                                                         | Percent Grade        | Note                                                                   |
+====================================================================+======================+========================================================================+
| [Worksheets](../worksheets.qmd)                                    | 20%                  | Four guided worksheets                                                 |
+--------------------------------------------------------------------+----------------------+------------------------------------------------------------------------+
| [Mini Data Analysis](../mda/mda_deliverable1.qmd)                  | 45%                  | Students write their own mini analysis                                 |
+--------------------------------------------------------------------+----------------------+------------------------------------------------------------------------+
| [Collaborative Project](../collabproj/collabproj_deliverable1.qmd) | 35%                  | Team project intended for practicing version control and collaboration |
+--------------------------------------------------------------------+----------------------+------------------------------------------------------------------------+

#### Worksheets

Worksheets are interactive assignments that allow students to get real-time feedback on their code. Your grade will be based on the number of correct answers provided. There are unlimited attempts for the worksheets, and time will be given in class to work through them. Worksheets are equally weights (each worth 5% if your final grade)

Worksheets are produced with Jupyter Notebooks, and will be submitted on Canvas.

+------------------------------------------------------------------------------------------------------------------------+----------------------+-----------------------+
| Worksheet                                                                                                              | Release Date         | Due Date (11:59PM PT) |
+========================================================================================================================+======================+=======================+
| [Worksheet A1](https://github.com/UBC-STAT/STAT545.github.io/blob/main/content/worksheets_student/worksheet_a01.ipynb) | September 2nd, 2025  | NA                    |
+------------------------------------------------------------------------------------------------------------------------+----------------------+-----------------------+
| [Worksheet A2](https://github.com/UBC-STAT/STAT545.github.io/blob/main/content/worksheets_student/worksheet_a02.ipynb) | September 15th, 2025 | September 22nd, 2025  |
+------------------------------------------------------------------------------------------------------------------------+----------------------+-----------------------+
| [Worksheet A3](https://github.com/UBC-STAT/STAT545.github.io/blob/main/content/worksheets_student/worksheet_a03.ipynb) | September 22nd, 2025 | September 29th, 2025  |
+------------------------------------------------------------------------------------------------------------------------+----------------------+-----------------------+
| [Worksheet A4](https://github.com/UBC-STAT/STAT545.github.io/blob/main/content/worksheets_student/worksheet_a04.ipynb) | September 29th, 2025 | October 13th, 2025    |
+------------------------------------------------------------------------------------------------------------------------+----------------------+-----------------------+
| [Worksheet A5](https://github.com/UBC-STAT/STAT545.github.io/blob/main/content/worksheets_student/worksheet_a05.ipynb) | October 13th, 2025   | October 20th, 2025    |
+------------------------------------------------------------------------------------------------------------------------+----------------------+-----------------------+

#### Collaborative Project

Teams will be randomly assigned. The idea behind the collaborative project is to practice using Version Control and collaborative tools on Github, troubleshoot broken R code, and rewrite code to address issues. There will be two deliverables for the project:

+-------------------------------------------------------------------------+----------------------+-----------------------+
| Collaborative Project Milestone                                         | Release Date         | Due Date (11:59pm PT) |
+=========================================================================+======================+=======================+
| [Deliverable 1](../collabproj/collabproj_deliverable1.qmd) (100 points) | September 4th, 2025  | September 19th, 2025  |
+-------------------------------------------------------------------------+----------------------+-----------------------+
| [Deliverable 2](../collabproj/collabproj_deliverable2.qmd) (78 points)  | September 4th, 2025  | September 26th, 2025  |
+-------------------------------------------------------------------------+----------------------+-----------------------+

Instructions will be posted on the Course Website under "Collaborative Project"

#### Mini Data Analysis

Conduct your own mini data analysis! The goal of this assignment is to become more familiar with R and generate a reproducible report using RMarkdown and various packages, such as `tibble`. There are two equally weighted deliverables:

+----------------------------------------------------------+----------------------+-----------------------+
| Mini Data Analysis Milestone                             | Release Date         | Due Date (11:59PM PT) |
+==========================================================+======================+=======================+
| [Deliverable 1](../mda/mda_deliverable1.qmd) (36 points) | September 26th, 2025 | October 3rd, 2025     |
+----------------------------------------------------------+----------------------+-----------------------+
| [Deliverable 2](../mda/mda_deliverable2.qmd) (36 points) | September 26th, 2025 | October 22nd, 2025    |
+----------------------------------------------------------+----------------------+-----------------------+

### Auditing Students

Auditing students are expected to complete all assessments (see above). All assessments are graded on a pass/fail basis for those officially auditing.

You must be registered as an auditing student to attend lectures due to capacity limitations.

### Course Communications

We will be using Slack as our primary platform of all course-related communications! Students will be emailed an invite to their class' Slack workspace.

Official course communications will occur on the `#announcements` channel. You will receive an invite on the first day of classes. Please notify the instructor by email if you have not received your personal invite.

Our STAT 545 team will be actively monitoring Slack during regular working hours (9am to 5pm PT, Monday to Friday). You are free to ask questions outside of this window but please keep in mind that there are no expectations for the team to answer questions outside of working hours or on weekends or holidays.

To make the most out of Slack, please

-   Use the `#general` channel for clarifications, asking about course organization, or clarifying instructions. Things you post on the `#general` channel will be seen by everyone, so please do not provide information that gives away answers to assignments.

-   Make a group chat with our TAs when you need more personalized help, or have an issue with grading. They may direct you to the `#general` channel when appropriate, or direct you to the instructor.

-   Direct message the instructor if there is a concern that is more personal (i.e., you need to self declare an absense) or if you have already talked to the TAs about an issue and are unsatisfied. You can also direct message the instructor if you are having issues with a group member in any group-related assignments.

-   Post in the `#random` channel if you find things related to the course that you'd like to share

### Privacy

Slack and GitHub are hosted on servers stored outside of Canada. Please keep this in mind.

### Policies

#### Regrade Requests

Regrade requests must be sent to the TAs through Slack within one week of the assessment being returned. If required, regrade requests can be escalated to the instructor [only if]{.underline} the request has already been brought up to the TA team and the student is unsatisfied. The instructor reserves the right to regrade the entire assessment, resulting in a higher or lower mark than originally provided.

#### Late Policies

Worksheets (and larger assignments, if applicable) are due at 11:59pm PT on the date indicated in the course schedule. For a late submission, a 24 hour extension will be provided for the first offense. Late submissions will be given a grade of 0 for subsequent occurrences.

**There is a zero-tolerance policy for late projects, including the mini data analysis and the collaborative project. If you are having issues with a team member regarding any group work, reach out to the instructor directly through Slack or email.**

#### Academic Concession

UBC no longer requires a doctor’s note (or supporting documentation) for [academic concession](http://www.calendar.ubc.ca/vancouver/index.cfm?tree=3,48,0,0). A self-declaration will suffice – [here is a template you can use](chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://biologyprogram-2023.sites.olt.ubc.ca/files/2024/10/Academic-Concession-Form-2022W.pdf). The form is also posted on our Canvas page. Please submit this to the instructor via email.

Examples of “conflicting responsibility” are conference travel and time-sensitive field work.

If you arrange to have an assignment submitted late, you may not be able to receive feedback from your peers.

#### Plagiarism

Plagiarism, which is intellectual theft, occurs where an individual submits or presents the oral or written work of another person as his or her own and can include:

-   multiple students submitting the same response

-   copying from sources without citing them

-   copying verbatim (word-for-word) from source and citing, but failing to make it explicit that this is a quotation (quotations should be used only rarely, if at all)

Students are responsible for ensuring that any work submitted does not constitute plagiarism. Students who are in any doubt as to what constitutes plagiarism should consult their instructor before handing in any assignments.

For more information see the [UBC Academic Misconduct policies](http://www.calendar.ubc.ca/vancouver/index.cfm?tree=3,54,111,959).

#### **Code Plagiarism**

Students must correctly cite any code that has been authored by someone else or by the student themselves for other assignments. Cases of code plagiarism may include, but are not limited to:

-   the reproduction (copying and pasting) of code with none or minimal reformatting (e.g., changing the name of the variables)

-   the translation of an algorithm or a script from a language to another

-   the generation of code by automatic code-generations software

An “adequate acknowledgement” requires a detailed identification of the (parts of the) code reused and a full citation of the original source code that has been reused.

#### UBC’s Policies and Resources to Support Student Success

UBC provides resources to support student learning and to maintain healthy lifestyles but recognizes that sometimes crises arise and so there are additional resources to access including those for survivors of sexual violence. UBC values respect for the person and ideas of all members of the academic community. Harassment and discrimination are not tolerated nor is suppression of academic freedom. UBC provides appropriate accommodation for students with disabilities and for religious, spiritual and cultural observances. UBC values academic honesty and students are expected to acknowledge the ideas generated by others and to uphold the highest academic standards in all of their actions. Details of the policies and how to access support are available [here](https://senate.ubc.ca/policies-resources-support-student-success).

#### Your personal health

**If you’re sick, it’s important that you stay home – no matter what you think you may be sick with (e.g., cold, flu, other).** Your precautions will help reduce risk and keep everyone safer. The structure of this class is intended to provide flexibility so that you can prioritize your health and still be able to succeed.

**If you do miss class because of illness:**

-   Consult the class resources on the course website

-   Come to office hours on Zoom.

-   Use Slack to carry out discussions.

If you miss an assessment due to illness, see the above section on Academic Concessions, and review the UBC policy here: <http://www.calendar.ubc.ca/vancouver/index.cfm?tree=3,329,0,0>

Above all, please take care of yourself and be kind to yourself and your classmates. If you or anyone you know experiences any academic stress, difficult life events, or feelings like anxiety or depression, I strongly encourage you to seek support. UBC Counseling Services is here to help: call 604 822 3811 or visit their website. Consider also reaching out to a friend, faculty member, or family member you trust to help get you the support you need.

#### Instructor health

If I am ill, then I will not come to class. If that happens, here’s what you can expect:

-   If I am well enough to teach, I will conduct virtual lectures through Zoom until I am well. If this happens, you will be tagged in an announcement via Slack with information. You can anticipate that this would very likely be a last minute announcement. Our classroom will still be available for you to sit and attend an online session, although it is recommended that you bring headphones.

-   If I am not well enough to teach, it is possible that one or more teaching assistants will take my place. But if not, we will either try to make up for lost time, make new resources to aid in your learning, or make accommodations regarding the assessments.

### Copyright

Course materials are licensed under [Creative Commons 4.0](https://creativecommons.org/licenses/by/4.0/).
