---
title: "Content and Schedule"
format: html
---

The schedule is subject to change at the discretion of the instructor. Any classes without a topic listed are working sessions with the TAs.

All due dates are at 11:59pm PT (local time, Vancouver).



**STAT 545 A**

| Week | Date | Notes | Assessments Due |
|------------------|------------------|------------------|------------------|
| 1 | Tues Sept 8 | (Optional) [Installation Help Session](lectures_i/lec1a_installation.qmd) |  |
|  | Thurs Sept 10 | [Introduction to R](lectures_i/lec1b_introR.qmd) |  |
| 2 | Tues Sept 15 | [Data Cleaning with `dplyr`](lectures_i/lec2a_dplyr.qmd) | |
|  | Thus Sept 17 | [RMarkdown and Reproducibility](lectures_i/lec2b_reproducibility.qmd) | Worksheet A1  |
| 3 | Tues Sept 22 | [Version Control I](lectures_i/lec3_versioncontrol.qmd) | |
|  | Thurs Sept 24 | [Version Control II](lectures_i/lec3_versioncontrol.qmd) | Worksheet A2  |
| 4 | Tues Sept 29 | [Data Visualization I](lectures_i/lec4_datavis.qmd) | |  |
|  | Thurs Oct 01 | [Data Visualization II](lectures_i/lec4_datavis.qmd)  | Collaborative Project |
| 5 | Tues Oct 06 | [Tidy Data](lectures_i/lec5_tidydata.qmd)  | Worksheet A3 |
|  | Thurs Oct 08 | [Model Fitting](lectures_i/lec6a_modelfitting.qmd)  |  |
| 6 | Tues Oct 13 | [Factors](lectures_i/lec6b_factorsanddates.qmd)  | Mini Data Analysis I |
|  | Thurs Oct 15 |  | Worksheet A4 |
| 7 | Tues Oct 20 | [Reading/Writing](lectures_i/lec7a_readwritedata.qmd) , [Tibble Joins](lectures_i/lec7b_joiningtibbles.qmd) |  |
|  | Thurs Oct 22 |  | Worksheet A5 |
|  | Tuesday Oct 27 |  | Mini Data Analysis II |
|  |  |  |  |

**STAT 545 B**

| Week | Date | Topic | Assessments Due |
|------------------|------------------|------------------|------------------|
| 1 | Tues Oct 27 | [Functions](lectures_ii/lec8a_functions.qmd)  |  |
|  | Thurs Oct 29 | [Advanced Functions](lectures_ii/lec8b_advfunctions.qmd) |  |
| 2 | Tues Nov 03 | [R Packages](lectures_ii/lec9_rpackages.qmd) | Worksheet B1 |
|  | Thus Nov 05 | Advanced R Packages | Assignment 1 (Functions) |
| 3 | ~~Tues Nov 10~~ | ~~**NO CLASS**~~ |  |
|  | Thurs Nov 12 | [Regular Expressions with `stringr`](lectures_ii/lec10_characterdata.qmd) |  |
| 4 | Tues Nov 17 | [Dashboards with `RShiny`](lectures_ii/lec11_shiny.qmd) | Assignment 2 (R Package) |
|  | Thurs Nov 19 |  | Worksheet B2 |
| 5 | Tues Nov 24 | [Iteration](lectures_ii/lec12_purrr.qmd) |  |
|  | Thurs Nov 26 |  | |
| 6 | Tues Dec 01 | [Websites with `quarto`](lectures_ii/lec13_quarto.qmd) | Assignment 3 (Dashboard)  |
|  | Thurs Dec 03 |  | Worksheet B3 |
|  | ... |  |  |
|  | Tues Dec 15 |  | Assignment 4 (Website) |
