---
title: "Worksheets"
date-modified: last-modified
---

Worksheets are guided exercises that are meant to supplement lectures, and will be graded as part of your final mark in STAT545.

Worksheets are produced with Jupyter Notebooks. For installation instructions, see [Lecture 1A (Installation)](lectures_i/lec1a_installation.qmd) or check out [t](https://www.youtube.com/watch?v=-jPaI1njy3E)[his YouTube video!](https://youtu.be/CdISUthp8dk)

[Worksheets will be posted on the dates given on the table!]{.underline}

[**Worksheet Tips and Tricks:**]{.underline}

-   Download the .ipynb file from GitHub and save it on your personal computer.

-   Only edit cells where prompted. If you accidentally click on a text-only cell, hit the play button and it should re-render.

-   You can check your answers prior to submitting! If you see a "Success!" message, you got the question right. Otherwise, a detailed error message will help you diagnose what went wrong.

-   Save your work frequently.

-   Prior to submitting, restart your kernel and run all to ensure that no errors persist. Save again.

-   Submit the .ipynb file to Canvas with the file name "worksheet_a##".

-   We're here to help along the way on Slack, so don't be shy to ask for help if you need it.

### **STAT 545 A**

| Worksheet | Release Date | Due Date (11:59PM PT) |
|------------------------|------------------------|------------------------|
| [Worksheet A1](https://github.com/UBC-STAT/STAT545.github.io/blob/main/content/worksheets_student/worksheet_a01.ipynb) | September 2nd, 2025 | NA |
| [Worksheet A2](https://github.com/UBC-STAT/STAT545.github.io/blob/main/content/worksheets_student/worksheet_a02.ipynb) | September 15th, 2025 | September 22nd, 2025 |
| [Worksheet A3](https://github.com/UBC-STAT/STAT545.github.io/blob/main/content/worksheets_student/worksheet_a03.ipynb) | September 22nd, 2025 | September 30th, 2025 (EXTENDED) |
| [Worksheet A4](https://github.com/UBC-STAT/STAT545.github.io/blob/main/content/worksheets_student/worksheet_a04.ipynb) | September 29th, 2025 | October 13th, 2025 |
| [Worksheet A5](https://github.com/UBC-STAT/STAT545.github.io/blob/main/content/worksheets_student/worksheet_a05.ipynb) | October 13th, 2025 | October 20th, 2025 |

### **STAT 545 B:**

| Worksheet | Release Date | Due Date (11:59PM PT) |
|----|----|----|
| [Worksheet B1](https://github.com/UBC-STAT/STAT545.github.io/blob/main/content/worksheets_student/worksheet_b01.ipynb) | Monday Oct 20, 2025 | Monday Oct 27, 2025 |
| Worksheet B2 | Friday Nov 14, 2025 | Monday Nov 24, 2025 |
| Worksheet B3 | Tuesday Nov 25, 2025 | Thursday Dec 4, 2025 |
